### ISSUE TITLE
Markdig Include extension

### ISSUE THREAD

**Issue by AceTheWiz** [cpfr/w3term#1]
Hi Carsten, apologies for hijacking this repo but I did not know how else to get hold of you.

It is actually about a comment you made [here ](https://github.com/xoofx/markdig/issues/67#issuecomment-335095806)

I was wondering if you can you possible share your solution ?

Thanks
Alan

**Comment by cpfr** [comment]
I wrote an answer in the thread you mentioned, but I'm afraid that I am not really able to help you, since I don't have the source code anymore and I am not able to remember the details, since this was more than three years ago.

**Comment by AceTheWiz** [comment]
Understood. Thank you for taking the time to answer.
